version: "2.2"
# Remain on v2 for https://github.com/docker/compose/issues/4513

volumes:
  musik:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Musik

  nas_fritzbox:
#    driver: cifs
#    driver_opts:
#      share: fritz.nas/fritz.nas/Fritz_NAS_HD
    driver: local
    driver_opts:
      type: none
      device: /mnt/fritz_nas_hd
      o: bind

  portainer:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/portainer-strom

  pi-hole_etc_pihole:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/pi-hole/etc_pihole

  pi-hole_etc_dnsmasq.d:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/pi-hole/etc_dnsmasq.d

  readymedia_cache:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/readymedia/cache

  readymedia_log:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/readymedia/log

#  serviio_library:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=192.168.6.22,nolock,rw
#      device: :/nfs/Data/linux/serviio/library
#
#  serviio_log:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=192.168.6.22,nolock,rw
#      device: :/nfs/Data/linux/serviio/log
#
#  serviio_transcode:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=192.168.6.22,nolock,rw
#      device: :/nfs/Data/linux/serviio/transcode

  strom:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/strom

networks:
  backend:
    driver: bridge

services:
  pi-hole:
    restart: unless-stopped
    build: pi-hole
#    image: diginc/pi-hole-multiarch:debian_armhf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80
      - 443:443
    environment:
      - ServerIP=192.168.6.6
      - WEBPASSWORD=1234
    volumes:
      - pi-hole_etc_pihole:/etc/pihole:nocopy
      - pi-hole_etc_dnsmasq.d:/etc/dnsmasq.d:nocopy

  portainer:
    restart: unless-stopped
    image: portainer/portainer
    ports:
      - 8008:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data:nocopy

  readymedia:
    restart: unless-stopped
    build:
      context: readymedia
      args:
        - CACHE_DATE=2018-07-16
    # Note: 'network_mode: host' is required for twonky to receive multicast traffic
    #       to detect the upnp server.
    network_mode: host
    ports:
      - 1900:1900/udp
      - 8895:8895/tcp
      - 8200:8200/tcp
    volumes:
      - musik:/musik:nocopy
      - nas_fritzbox:/nas_fritzbox:nocopy
      - readymedia_cache:/var/cache/minidlna
      - readymedia_log:/var/log/minidlna

#  serviio:
#    restart: unless-stopped
#    build:
#      context: serviio
#      args:
#        - CACHE_DATE=2018-07-16
#    cpu_count: 1
##          memory: 50M
#    # Note: 'network_mode: host' is required for twonky to receive multicast traffic
#    #       to detect the upnp server.
## try without    network_mode: host
#    ports:
#      - 1900:1900/udp
#      - 8895:8895/tcp
#      - 23423:23423/tcp
## mediabrowser      - 23424:23424/tcp
#    volumes:
#      - musik:/musik:nocopy
#      - nas_fritzbox:/nas_fritzbox:nocopy
#      - serviio_log:/serviio/log:nocopy
#      - serviio_library:/serviio/library:nocopy
#      - serviio_transcode:/serviio/transcode:nocopy

  strom:
    restart: unless-stopped
    build:
      context: strom
      args:
        - CACHE_DATE=2018-04-18
    ports:
      - 9083:9083
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    networks:
      - backend
    volumes:
      - strom:/var/strom:nocopy
#    links:
#      - postfix
#      - pigpiod

  stubby:
    restart: unless-stopped
    build:
      context: stubby
      args:
        - CACHE_DATE=2018-07-15
    ports:
#     - 127.0.0.1:53:53/tcp
#     - 127.0.0.1:53:53/udp
     - 6653:6653/tcp
     - 6653:6653/udp
    networks:
      - backend
