version: "3"

volumes:
  strom:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.6.22,nolock,rw
      device: :/nfs/Data/linux/strom

networks:
  backend:
    driver: bridge

services:
  strom:
    restart: unless-stopped
    build:
      context: strom
      args:
        - CACHE_DATE=2018-04-18
    ports:
      - 9083:9083
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    networks:
      - backend
    volumes:
      - strom:/var/strom:nocopy
#    links:
#      - postfix
#      - pigpiod
